apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ops

helmCharts:
- name: paperless-ngx
  version: 0.24.1
  releaseName: paperless-ngx
  repo: https://charts.gabe565.com
  valuesFile: values.yaml
