apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ops

helmCharts:
- name: paperless-ngx
  version: 7.8.23
  releaseName: paperless-ngx
  repo: oci://ghcr.io/gabe565/charts
  valuesFile: values.yaml
