apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-cloudflare
spec:
  encryptedData:
    apitoken: AgBm5WDiXVbatjxiHkdtutFTh+9lt8jfao6oXwhDckM/a4/83o5OE08Ltl93AdUkd2JoBITbcOpop9vZQ/MGLR1JLY9m2Ay6gkeQjQwscG5/FlR6t9LZXRCgCjb8r2HSOfEDuRgMwAanl/4QsZryFgBMJrWE6t2qdb6a0lVVYPhXLbubaoWiVF70j4YULl9aqlr7fEgbNIguG5NiPfujLGMlIh7WYsTZCQyM1VVam8sJbN8WPr0OxSMdj/FtCAcdxX0aJf76SEGbIkhIE3ETSZREQfyn55iIxDDwpHUet7Ju39i7dhMoA4Y/SoRyUU99x76WopBLgaXgQkSQjMCWSuCNuwDbiQrWxOPc9wcsvRySCle8066ExzHQTQaMZ1xFu8cGMdQ8LiyxDHKjz9/bJsOdiK/E0whe2nCZdnDG5IVeiSX+Ft3ijwxMyycHQDK2GDQ80JzTJ6LerusTIgnenCVQCX4TVRCRbwlcUX8BiBkMJR6p9iTNiRlIIx5pKbdPWhwA0nhEg2RpkN24lzKEPOAb3LKtzGDL5/jVdTkzQ9l6wM9V0EiGS8wbQ53+tBcblMMJ7uUIFEoAVbr6ZADlzB5beHPIkn0AeFYCnBqCVpLK7iWKU47cox4wg1/89Weon7iec+DGpRxYsvVdhOCE6+3CbR5K9xwAIj21MttnUw+BoT5oJ0Gfhhh1JvQf+OM41GYC3yfmgiw2Nb3cWIXvHvVBkHRFHTu2rScDl+qAKNBpHbZjE9iL80yJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: laurinstreng1@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-acme-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: apitoken
            name: cert-manager-cloudflare
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-streng-it.org
spec:
  secretName: wildcard-streng-it.org
  dnsNames:
  - streng-it.org
  - '*.streng-it.org'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
