apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-cloudflare
spec:
  encryptedData:
    apitoken: AgAavs5HgEArUm9JswsKUNf72LC5qU21bnBpQr/1O1Y6Ck4SNuwYjUJmtXjf2CdrHL3XaZCX1OpIKggtoDG11vhI0CcpfdceYsIw9K47WmtQmg5N4o/sNBvhDS5aq7yJHTY0VxfDFqwNJ3pERckFW10mjzLg8BP2QNxUx/17QZeUN9uPl1oQFkBCeJgWA98EztHTKWV1MGJauon2iXywt8zon1QCQ5YgQCT+JgW9KC8gWioV0Sd9/tMcKz5zXfXwr9fGan4gw2wi4UOdNe6hI/XNBF0kmqR3DTnbXpYHSuD/bp9KgW6uYihNW06UlVI4EuTINokh1m5RmsY/TvHQ2R8JMOFto5d74c4rYqd1ndG7+CFnmlqqfUp8G4cuASRDE4qXWp21JMZn6aoH6bU8irMxJp4AfxCw++YKYrwiY82sEtvCIgPAH4+IwzVyMayxgPX2hVFTgqeI4s5TX8gN+iZa1T5+jKuJX1rBtqs8VdIE7KAIwJt8RYw9f5zopJUi832PkUdMLR7QRCkv4F8ZGx+tc3bSs2trPpE0xP0Its0Fz4HnacOGnFiMGnFDPVPKeS5kmKVNxSKTarrUgRP5OIJV+97c1NGWDA5bwdCi764bKFIwHryWTu6tpLeiTqG4uIIctTxwpECGVfQG9lQmw5/VXK0VaK2upEQ/MNI8vdhEmXKaXgWhZYegK6KokdYeoVxzO4RPGxFJ5lF4INndpw326q0Mw46ianjagrUDI0hTqSXnyq8vhFyZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: laurinstreng1@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-acme-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: apitoken
            name: cert-manager-cloudflare
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-streng-it.org
spec:
  secretName: wildcard-streng-it.org
  dnsNames:
  - streng-it.org
  - '*.streng-it.org'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
