---
# Setup Network UPS Tools

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - nut
      - nut-client
      - nut-server
    state: "present"

- name: Install NUT configuration files.
  ansible.builtin.template:
    src: "ups.conf.j2"
    dest: "/etc/nut/ups.conf"
    owner: root
    group: nut
    mode: 0640
  notify: Restart nut
