ipam:
  mode: kubernetes

kubeProxyReplacement: true

securityContext:
  capabilities:
    ciliumAgent: 
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState: 
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE

cgroup:
  hostRoot: /sys/fs/cgroup
  autoMount:
    enabled: false

l2announcements:
  enabled: true

k8sClientRateLimit:
  qps: 15
  burst: 30

hubble:
  listenAddress: ":4244"
  peerService:
    targetPort: 4244
  tls:
    auto:
      enabled: true
      method: helm
      certValidityDuration: 1095
      # Cannot Use Certmanager Currently because the Common Name in the CertRequest are Static to cilium.io
      # method: certmanager
      # certValidityDuration: 1095
      # certManagerIssuerRef:
      #   group: cert-manager.io
      #   kind: ClusterIssuer
      #   name: letsencrypt
  ui:
    enabled: true

  relay:
    enabled: true

l7Proxy: true

# to disable the Namespace Creation via the Helm Chart
secretsNamespace:
  create: false
  name: network

ingressController:
  enabled: false
  secretsNamespace:
    create: false

gatewayAPI:
  enabled: false
  secretsNamespace:
    create: false

envoyConfig:
  enabled: false
  secretsNamespace:
    create: false

bgpControlPlane:
  enabled: false
  secretsNamespace:
    create: false

tls:
  secretsNamespace:
    create: false
