apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
    {{- with .Values.labels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
