apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/domain.yaml

namespace: network

helmCharts:
- repo: https://charts.jetstack.io
  name: cert-manager
  version: v1.17.1
  includeCRDs: true
  releaseName: cert-manager
  valuesFile: values.yaml
  namespace: network
