configs:
  cm:
    kustomize.buildOptions: --enable-helm
    url: argocd.streng-it.org
  params:
    controller.diff.server.side: "true"

global:
  hostAliases:
  - ip: 192.168.178.101
    hostnames:
    - streng-it.org

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    hostname: streng-it.org
