configs:
  cm:
    kustomize.buildOptions: --enable-helm
    url: https://argocd.streng-it.org
  params:
    controller.diff.server.side: "true"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    hostname: argocd.streng-it.org
