---
clusterName: homelab
endpoint: https://192.168.178.136:6443
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

# I use cilium as a CNI
cniConfig:
  name: none
nodes:
  - hostname: master
    controlPlane: true
    ipAddress: 192.168.178.136
    installDisk: /dev/nvme0n1
    talosImageURL: ghcr.io/laurinstreng/talos-orangepi-5:v1.9.1

  - hostname: worker-1
    ipAddress: 192.168.178.135
    installDisk: /dev/nvme0n1
    talosImageURL: ghcr.io/laurinstreng/talos-orangepi-5:v1.9.1

  - hostname: worker-2
    ipAddress: 192.168.178.137
    installDisk: /dev/nvme0n1
    talosImageURL: ghcr.io/laurinstreng/talos-orangepi-5:v1.9.1
