---
- name: "Install unattended-upgrades"
  ansible.builtin.apt:
    pkg: "unattended-upgrades"
    state: "present"

- name: "Ensure APT periodic updates are configured"
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |-
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
