---
- name: General Setup
  hosts: all
  become: true
  tasks:
    - name: Install unanted-upgrades
      ansible.builtin.include_role:
        name: unanted_upgrades

# - name: Setup AdGuardHome
#  hosts: adguard
#  become: true
#  tasks:
    #    - name: Include adguard role
    #      include_role:
    #        name: adguard

- name: Setup Pi-UPS
  hosts: pi-ups
  become: true
  tasks:
    - name: Setup Network UPS Tools
      ansible.builtin.include_role:
        name: nut
