---
- hosts: all
  become: yes
  tasks:
#    - name: Include adguard role
#      include_role:
#        name: adguard
    - name: Install unanted-upgrades
      include_role:
        name: unanted_upgrades

- hosts: all
  become: yes
  tasks:
    - name: Setup Network UPS Tools
      include_role:
        name: nut