metrics:
  main:
    enabled: false

blocky:
  enablePrometheus: false

queryLog:
  type: "" # Log to sdtout

cnpg:
  main:
    enabled: false

configmap:
  dashboard:
    enabled: false

  datasource:
    enabled: false

k8sgateway:
  enabled: true
  domain:
    - domain: streng-it.org

service:
  blocky-dns:
    loadBalancerIP: 192.168.178.101