metrics:
  main:
    enabled: false

blocky:
  enablePrometheus: false

queryLog:
  type: "" # Log to sdtout

cnpg:
  main:
    enabled: false

configmap:
  dashboard:
    enabled: false

  datasource:
    enabled: false

k8sgateway:
  enabled: true
  domain:
  - domain: "streng-it.org"

service:
  dns:
    type: LoadBalancer
    loadBalancerIP: 192.168.178.101