metrics:
  main:
    enabled: false

blocky:
  enablePrometheus: false

queryLog:
  type: "" # Log to sdtout

cnpg:
  main:
    enabled: false

configmap:
  dashboard:
    enabled: false

  datasource:
    enabled: false

k8sgateway:
  enabled: true
  domains:
  - domain: "streng-it.org"
    dnsChallenge:
      enabled: false
  watchedResources: ["Ingress"]

service:
  dns:
    type: LoadBalancer
    loadBalancerIP: 192.168.178.101

rbac:
  main:
    # -- Enables or disables the ClusterRole and ClusterRoleBinding
    enabled: true
    primary: true
    clusterWide: true
    # -- Set Rules on the ClusterRole
    rules:
      - apiGroups:
          - ""
        resources:
          - services
          - namespaces
        verbs:
          - list
          - watch
      - apiGroups:
          - extensions
          - networking.k8s.io
        resources:
          - Ingress
          - ingresses
        verbs:
          - list
          - watch
          - get